In [1]:
import plotly
import pandas as pd
import plotly.express as px
import plotly.io as pio
pio.renderers.default = 'browser'
import numpy as np

In [12]:
direc1 = "/media/linx123-rtx/Elements/test5/day1/analysis/3Dtracks/V13 to foraging (single)_CR3000x2 1838-ST-159160_1.csv"
direc2 = "/media/linx123-rtx/Elements/test5/day1/analysis/3Dtracks/V13 to foraging (single)_CR3000x2 1838-ST-159161_1.csv"
transform = False


R = np.array([[-0.01569649,  0.99946256,  0.02877858],
 [-0.12604994, -0.03053046,  0.99155398],
 [ 0.99189971,  0.01193638,  0.12646142]])

T = np.array([[4.44749048],
 [-1793.30879377],
 [1603.7252569 ]])

K = np.array([[3.00e+03, 0.00e+00, 8.48e+02],
 [0.00e+00, 3.00e+03, 8.55e+02],
 [0.00e+00, 0.00e+00, 1.00e+00]])


df = pd.read_csv(direc1)
df["size"] = [2]*len(df["x"])
df["camerapair"] = [1]*len(df["x"])
df2 = pd.read_csv(direc2)
df2["size"] = [2]*len(df2["x"])
df2["camerapair"] = [2]*len(df2["x"])



if transform == False:
    Tmatrix = np.append(np.append(R,T,axis=1),np.array([0,0,0,1])).reshape(4,4)
    for i,(x,y,z) in enumerate(zip(df["x"],df["y"],df["z"])):
        pt = np.array([x,y,z,1])
        # transformation
        Tpt = Tmatrix.dot(pt)
        Tpt = Tpt / Tpt[3]
        #print(Tpt)
        df.at[i,'x']=Tpt[0]
        df.at[i,'y']=Tpt[1]
        df.at[i,'z']=Tpt[2]
    for i,(x,y,z) in enumerate(zip(df2["x"],df2["y"],df2["z"])):
        pt = np.array([x,y,z,1])
        #print(pt)
        # transformation
        Tpt = Tmatrix.dot(pt)
        print(Tpt)
        Tpt = Tpt / Tpt[3]
        #print(Tpt)
        df2.at[i,'x']=Tpt[0]
        df2.at[i,'y']=Tpt[1]
        df2.at[i,'z']=Tpt[2]        
        
    df = df.append(df2)
    df["ID"] = df["ID"].astype(str)
    # plot 3d plot
    fig = px.scatter_3d(df, x='x', y='y', z='z',
              color='camerapair', size='size', size_max=8,
              symbol='ID', opacity=0.7)
    
    fig.update_layout(
        scene = {"aspectmode":"manual","aspectratio":dict(y=1, x=8/3, z=1),
                "yaxis":dict(nticks=4, range=[-100,200],),
                "xaxis":dict(nticks=4, range=[500,-300],),
                "zaxis":dict(nticks=4, range=[1960,1660],)})
    
    fig.update_layout()

    camera = dict(
        up=dict(y=0, x=0, z=0),
        center=dict(y=0, x=0, z=-21), # z is the focal length in millimeter, f_mm = f_pixel * sensor_height_mm / image_height_pixel
        eye=dict(x=0, y=0, z=0)
    )

    fig.update_layout(scene_camera=camera)
    fig.show()
else:
    df = df.append(df2)
    df["ID"] = df["ID"].astype(str)
    # plot 3d plot
    fig = px.scatter_3d(df, x='x', y='y', z='z',
              color='camerapair', size='size', size_max=8,
              symbol='ID', opacity=0.7)

    fig.update_layout(
        scene = {"aspectmode":"manual","aspectratio":dict(x=1, y=8/3, z=1),
                "xaxis":dict(nticks=4, range=[30,-270],),
                "yaxis":dict(nticks=4, range=[-400,400],),
                "zaxis":dict(nticks=4, range=[1960,1660],)})
    fig.update_layout()

    camera = dict(
        up=dict(y=0, x=0, z=0),
        center=dict(y=0, x=0, z=-21),# z is the focal length in millimeter, f_mm = f_pixel * sensor_height_mm / image_height_pixel
        eye=dict(x=0, y=0, z=0)
    )

    fig.update_layout(scene_camera=camera)
    fig.show()

[4.24475274e+02 1.57141498e+01 1.75694912e+03 1.00000000e+00]
[-1.05947942e+02 -1.03534718e+02  1.71529871e+03  1.00000000e+00]
[-8.21391523e+01 -1.02872548e+02  1.76366124e+03  1.00000000e+00]
[-1.08389750e+02 -1.05151834e+02  1.71401947e+03  1.00000000e+00]
[4.22927306e+02 1.54052365e+01 1.75662026e+03 1.00000000e+00]
[-8.32758665e+01 -1.04535931e+02  1.76343313e+03  1.00000000e+00]
[4.20889698e+02 1.59111957e+01 1.75425474e+03 1.00000000e+00]
[-1.09396192e+02 -1.04801246e+02  1.71741051e+03  1.00000000e+00]
[-8.06726096e+01 -1.05203011e+02  1.76400260e+03  1.00000000e+00]
[4.19224687e+02 1.64926737e+01 1.75243263e+03 1.00000000e+00]
[-7.81569471e+01 -1.04093492e+02  1.76527518e+03  1.00000000e+00]
[-1.11212600e+02 -1.03723055e+02  1.71912136e+03  1.00000000e+00]
[4.18543099e+02 1.70295460e+01 1.75128395e+03 1.00000000e+00]
[-7.47647286e+01 -1.02380895e+02  1.76606310e+03  1.00000000e+00]
[-1.12417740e+02 -1.03820180e+02  1.72078359e+03  1.00000000e+00]
[-7.16044697e+01 -1.01816065e+

In [130]:
for col in df["x"]:
    print(col)

-80.00902077081153
-80.49463691598339
-80.96442936794627
-80.20656043650752
-79.74037627789079
-79.59560132036592
-78.27560339417856
-77.24806227169918
-76.49478015900482
-75.76189738814217
-75.36401725681424
-74.34808578690797
-73.31207952848808
-72.36662207676602
-70.74951423090367
-69.75709798251093
-69.04747395314355
-67.1459237792933
-65.2702863414094
-64.35072777557565
-63.40551830055243
-61.89787541319483
-60.69211793642998
-59.20628351995825
-57.72683518255874
-56.5333645136226
-54.46940153334244
-52.74141678231548
-52.150812189983775
-51.31864909753465
-50.1713366892405
-48.728124806240665
-47.57330253460636
-47.29312222672788
-47.01542363307091
-46.15957590599783
-45.330576326889584
-45.62417539820209
-45.54505946832544
-45.829590103353695
-46.33733447147184
-47.08658063602433
-48.47190786651058
-49.43519490068591
-50.47797187789967
-51.22104589882362
-52.610747432088445
-54.75855106741109
-56.33279609118796
-59.309746306882445
-61.51488028323045
-64.4877878064373
-67.7570616

In [194]:
Tmatrix

array([[-1.56964905e-02, -1.26049943e-01,  9.91899708e-01,
         9.99462565e-01],
       [-3.05304657e-02,  1.19363789e-02,  2.87785746e-02,
         9.91553988e-01],
       [ 1.26461417e-01,  4.44749048e+00, -1.79330879e+03,
         1.60372526e+03],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [197]:
pt.T.dot(Tmatrix)

array([ 2.11466053e+01,  1.41373969e+03, -6.62113305e+05,  5.95478288e+05])

In [238]:
3000/1696*12

21.22641509433962

array([-1.56964905e-02, -1.26049943e-01,  9.91899708e-01,  4.44749048e+00,
        9.99462565e-01, -3.05304657e-02,  1.19363789e-02, -1.79330879e+03,
        2.87785746e-02,  9.91553988e-01,  1.26461417e-01,  1.60372526e+03,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00])

In [210]:
np.append(R,T,axis=1)

array([[-1.56964905e-02, -1.26049943e-01,  9.91899708e-01,
         4.44749048e+00],
       [ 9.99462565e-01, -3.05304657e-02,  1.19363789e-02,
        -1.79330879e+03],
       [ 2.87785746e-02,  9.91553988e-01,  1.26461417e-01,
         1.60372526e+03]])

In [206]:
R

array([[-0.01569649, -0.12604994,  0.99189971],
       [ 0.99946256, -0.03053047,  0.01193638],
       [ 0.02877857,  0.99155399,  0.12646142]])